export const developerRoleDefinition = {
  cluster_permissions: [
    'cluster:monitor/nodes/info',
    'cluster:monitor/state',
    'cluster:monitor/health',
    'cluster_composite_ops_ro',
    'indices:data/write/bulk',
    'cluster:admin/opendistro/reports/definition/create',
    'cluster:admin/opendistro/reports/definition/update',
    'cluster:admin/opendistro/reports/definition/on_demand',
    'cluster:admin/opendistro/reports/definition/delete',
    'cluster:admin/opendistro/reports/definition/get',
    'cluster:admin/opendistro/reports/definition/list',
    'cluster:admin/opendistro/reports/instance/list',
    'cluster:admin/opendistro/reports/instance/get',
    'cluster:admin/opendistro/reports/menu/download',
  ],
  index_permissions: [
    {
      index_patterns: ['*'],
      dls: '',
      fls: [],
      masked_fields: [],
      allowed_actions: [
        'indices:data/read/search*',
        'indices:data/read/get',
        'indices:admin/get',
        'indices:admin/aliases/get',
        'indices:monitor/settings/get',
        'indices:monitor/stats',
        'indices:data/read/search/template',
        'data_access',
        'read',
        'search',
        'get',
        'indices_all',
      ],
    },
    {
      index_patterns: [
        '.kibana',
        '.kibana-6',
        '.kibana_*',
        '.opensearch_dashboards',
        '.opensearch_dashboards-6',
        '.opensearch_dashboards_*',
      ],
      dls: '',
      fls: [],
      masked_fields: [],
      allowed_actions: ['read', 'delete', 'manage', 'index'],
    },
    {
      index_patterns: ['.tasks', '.management-beats'],
      dls: '',
      fls: [],
      masked_fields: [],
      allowed_actions: ['indices_all'],
    },
  ],
  tenant_permissions: [
    {
      tenant_patterns: ['global_tenant'],
      allowed_actions: ['kibana_all_write'],
    },
  ],
};
