global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ec2'
    ec2_sd_configs:
      - region: us-east-2
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Prometheus]
        action: keep
        regex: true
      - source_labels: [__meta_ec2_private_ip]
        target_label: __address__
        replacement: $1:9100

remote_write:
  - url: REPLACE_ME
    sigv4:
      region: us-east-2
